# note, the sso is a hardcoded route to enable easy access but is "guessable"
apiVersion: cloud.redhat.com/v1alpha1
kind: FrontendEnvironment
metadata:
  name: env-boot 
spec:
  sso: 'https://keycloak-dev-sso.apps.markmc-dec-13.7i5s.p1.openshiftapps.com/auth/'
  ingressClass: openshift-default
  hostname: env-boot.apps.markmc-dec-13.7i5s.p1.openshiftapps.com
   
